# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_uuid', models.CharField(blank=True, db_column='link_uuid', db_index=True, max_length=100, null=True, verbose_name='\u552f\u4e00\u8bc6\u522b\u7801')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True, verbose_name='\u8c1c\u9898')),
                ('content', models.TextField(blank=True, db_column='content', null=True, verbose_name='\u5185\u5bb9')),
                ('answer', models.TextField(blank=True, db_column='answer', null=True, verbose_name='\u7b54\u6848')),
                ('qr_code', models.ImageField(blank=True, db_column='qr_code', null=True, upload_to='QRcode', verbose_name='\u4e8c\u7ef4\u7801')),
                ('solve_times', models.IntegerField(blank=True, db_column='solve_times', default=0, null=True, verbose_name='\u901a\u5173\u4eba\u6570')),
                ('previous_puzzle', models.ForeignKey(blank=True, db_column='previous_puzzle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Game.Puzzle', verbose_name='\u524d\u4e00\u4e2a\u8c1c\u9898')),
            ],
            options={
                'db_table': 'puzzle',
                'verbose_name': '\u8c1c\u9898',
                'verbose_name_plural': '\u8c1c\u9898',
            },
        ),
    ]
