# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='next_puzzle_n_hint',
            field=models.TextField(blank=True, db_column='next_puzzle_n_hint', null=True, verbose_name='\u4e0b\u4e2a\u8c1c\u9898\u548c\u63d0\u793a'),
        ),
    ]
